[package]
name = "ice"
version = "0.1.0"
edition = "2021"

[lib]
name = "ice"
path = "src/lib.rs"

[[bench]]
name = "ice_bench"
harness = false

# [[bench]]
# name = "icefast_bench"
# harness = false

[dependencies]
# Windows alloc is noticably slower than the mimalloc allocator
mimalloc = { version = "*", default-features = false }
rayon = "1.11.0"

[dev-dependencies]
divan = "0.1.21"

[profile.release]
debug = true
lto = true
codegen-units = 1
opt-level = 3
